#!/usr/bin/env ruby

require File.expand_path("../config/environment", File.dirname(__FILE__))

Advertisement.expired_advertisement.each do |advertisement|
  advertisement.send_advertisement_expired_mail
end
