#!/usr/bin/env ruby
require 'tmpdir'
lock_file = File.open(File.join(Dir.tmpdir, 'export_all.lock'), 'w')
unless lock_file.flock(File::LOCK_EX|File::LOCK_NB)
  exit 1
end

load "#{File.dirname(__FILE__)}/export"

if __FILE__ == $0
  configuration = Rails::Initializer.run(:initialize_logger).configuration
  @exporter = CMSExport.new
  @exporter.logger = Logger.new(File.join(File.dirname(configuration.log_path), 'export_all.log'))
  @exporter.create_all_page
end
