#!/usr/bin/env ruby
exit 1 unless ARGV.size == 2
exit unless File.exist?('/var/share/cms/do_export')

remote_host = ARGV[1]
lock_file = File.open(File.expand_path("../#{File.basename(ARGV[0])}", File.dirname(__FILE__)), 'w')
unless lock_file.flock(File::LOCK_EX|File::LOCK_NB)
  $stderr.puts 'another sync process is running.'
  exit
end

system("rsync -aLz --delete --exclude='*.md5' --exclude=.svn /var/share/cms/public./ #{remote_host}:/var/www/cms/")
