# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 70) do

  create_table "access_counts", :force => true do |t|
    t.column "datetime", :datetime
    t.column "genre_id", :integer
    t.column "page_id", :integer
    t.column "section_id", :integer
    t.column "path", :text
    t.column "count", :integer
    t.column "count_inside", :integer
  end

  add_index "access_counts", ["datetime"], :name => "access_counts_datetime_index"
  add_index "access_counts", ["path"], :name => "access_counts_path_index"

  create_table "board_comments", :force => true do |t|
    t.column "board_id", :integer, :null => false
    t.column "body", :text, :null => false
    t.column "from", :string, :null => false
    t.column "public", :boolean
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "remote_addr", :string
  end

  create_table "boards", :force => true do |t|
    t.column "title", :string, :null => false
    t.column "section_id", :integer, :null => false
  end

  create_table "divisions", :force => true do |t|
    t.column "name", :string
    t.column "number", :integer
    t.column "enable", :boolean
  end

  create_table "emergency_infos", :force => true do |t|
    t.column "display_start_datetime", :datetime, :null => false
    t.column "display_end_datetime", :datetime, :null => false
    t.column "content", :text, :null => false
  end

  create_table "enquete_answer_items", :force => true do |t|
    t.column "answer_id", :integer, :null => false
    t.column "enquete_item_id", :integer, :null => false
    t.column "value", :text
  end

  create_table "enquete_answers", :force => true do |t|
    t.column "page_id", :integer, :null => false
    t.column "answered_at", :datetime, :null => false
    t.column "remote_addr", :string, :null => false
  end

  create_table "enquete_items", :force => true do |t|
    t.column "page_id", :integer, :null => false
    t.column "no", :integer
    t.column "name", :string
  end

  create_table "genres", :force => true do |t|
    t.column "parent_id", :integer
    t.column "name", :string
    t.column "title", :string
    t.column "path", :string
    t.column "description", :text
    t.column "original_id", :integer
    t.column "no", :integer
    t.column "uri", :text
    t.column "section_id", :integer
  end

  add_index "genres", ["parent_id"], :name => "genres_parent_id_index"
  add_index "genres", ["path"], :name => "genres_path_index"
  add_index "genres", ["section_id"], :name => "genres_section_id_index"

  create_table "infos", :force => true do |t|
    t.column "title", :string
    t.column "last_modified", :datetime
    t.column "content", :text
  end

  create_table "jobs", :force => true do |t|
    t.column "datetime", :datetime
    t.column "action", :string
    t.column "arg1", :string
    t.column "arg2", :string
  end

  add_index "jobs", ["action"], :name => "jobs_action_index"
  add_index "jobs", ["arg1"], :name => "jobs_arg1_index"

  create_table "mailmagazine_contents", :force => true do |t|
    t.column "section_id", :integer
    t.column "mailmagazine_id", :integer
    t.column "title", :string
    t.column "content", :text
    t.column "datetime", :datetime
    t.column "send_mailmagazine_id", :integer
    t.column "no", :integer
  end

  create_table "mailmagazines", :force => true do |t|
    t.column "section_id", :integer
    t.column "mail_address", :string
    t.column "header", :text
    t.column "footer", :text
  end

  create_table "news", :force => true do |t|
    t.column "page_id", :integer
    t.column "published_at", :datetime, :null => false
    t.column "title", :string, :null => false
  end

  create_table "page_contents", :force => true do |t|
    t.column "page_id", :integer
    t.column "content", :text
    t.column "begin_date", :datetime
    t.column "end_date", :datetime
    t.column "last_modified", :datetime
    t.column "mobile", :text
    t.column "news_title", :string
    t.column "user_name", :string
    t.column "tel", :string
    t.column "email", :string
    t.column "comment", :text
    t.column "admission", :integer, :default => 0
    t.column "top_news", :integer, :default => 0
    t.column "section_news", :integer, :default => 0
  end

  add_index "page_contents", ["page_id"], :name => "page_contents_page_id_index"

  create_table "page_links", :force => true do |t|
    t.column "page_content_id", :integer
    t.column "link", :text
  end

  add_index "page_links", ["link"], :name => "page_links_link_index"

  create_table "page_locks", :force => true do |t|
    t.column "page_id", :integer
    t.column "status", :integer
    t.column "user_id", :integer
    t.column "time", :datetime
    t.column "session_id", :string
  end

  create_table "pages", :force => true do |t|
    t.column "genre_id", :integer
    t.column "name", :string
    t.column "title", :string
  end

  add_index "pages", ["genre_id"], :name => "pages_genre_id_index"

  create_table "sections", :force => true do |t|
    t.column "code", :string
    t.column "name", :string
    t.column "place_code", :integer
    t.column "info", :text
    t.column "top_genre_id", :integer
    t.column "number", :integer
    t.column "link", :string
    t.column "division_id", :integer
  end

  create_table "sent_mailmagazines", :force => true do |t|
    t.column "datetime", :datetime
    t.column "mailmagazine_id", :integer
    t.column "title", :string
    t.column "content", :text
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "name", :string
    t.column "section_id", :integer
    t.column "login", :string
    t.column "password", :string
    t.column "authority", :integer
    t.column "mail", :string
  end

  create_table "words", :force => true do |t|
    t.column "base", :string
    t.column "text", :string
    t.column "updated_at", :datetime, :null => false
    t.column "user_id", :integer
  end

  add_index "words", ["text"], :name => "words_text_index"

end
